# Generated by Django 3.1.7 on 2022-08-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='was_send_tg_message',
            field=models.BooleanField(default='True'),
        ),
    ]
