# Generated by Django 3.1.7 on 2022-08-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0003_order_was_send_tg_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='was_send_tg_message',
        ),
    ]
